name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04] # TODO: windows-latest & macos-latest
        channel: [stable]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Cache cargo registry
      uses: actions/cache@v3
      with:
        path: ~/.cargo/registry
        key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}

    - name: Cache cargo git index
      uses: actions/cache@v3
      with:
        path: ~/.cargo/git
        key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Install Vulkan on Linux
      if: runner.os == 'Linux'
      run: |
        wget -qO- https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo tee /etc/apt/trusted.gpg.d/lunarg.asc
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-noble.list http://packages.lunarg.com/vulkan/lunarg-vulkan-noble.list
        sudo apt update
        sudo apt install vulkan-sdk

    - name: Install Vulkan SDK on macOS
      if: runner.os == 'macOS'
      run: |
        brew update
        brew install --cask vulkan-sdk
        
    - name: Install Vulkan SDK on Windows
      if: runner.os == 'Windows'
      shell: pwsh
      run: |
        choco install vulkan-sdk -y
        # Ensure the installer’s environment variables are loaded:
        refreshenv

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Build release
      if: matrix.channel == 'stable'
      run: cargo build --release

    - name: Upload Release Binary
      uses: actions/upload-artifact@v4
      with:
        name: iVy-raytracer-rs-${{ runner.os }}
        path: target/release/iVy

