name: Rust CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-latest]
        channel: [stable]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4
        
    - name: Setup Vulkan headers & loader
      uses: humbletim/setup-vulkan-sdk@v1.2.1
      with:
        vulkan-query-version: latest
        vulkan-components: Vulkan-Headers, Vulkan-Loader
        vulkan-use-cache: true

    - name: Build
      run: cargo build --verbose

    - name: Run tests
      run: cargo test --verbose

    - name: Build release
      if: matrix.channel == 'stable'
      run: cargo build --release

    - name: Upload Release Binary (Linux)
      if: matrix.channel == 'stable' && runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: ivy-raytracer-rs-${{ runner.os == 'Windows' && 'windows' || runner.os == 'macOS' && 'macos' || 'linux' }}
        path: target/release/iVy${{ runner.os == 'Windows' && '.exe' || '' }}

